---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "control-hub.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "control-hub.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "control-hub.chart" . }}
data:
