{{- if (.Values.ingress.enabled) and not .Values.ingress.istio -}}
{{- $serviceName := include "control-hub.fullname" . -}}
{{- $servicePort := .Values.service.port -}}
{{- $adminPort := .Values.service.adminPort -}}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "control-hub.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "control-hub.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "control-hub.chart" . }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}.{{ .Values.ingress.domain }}
      http:
        paths:
        - path: /
          backend:
            serviceName: "{{ $serviceName }}-security" # security app can host UI for now
            servicePort: {{ $servicePort }}
        {{- range $app := .Values.apps }}
        - path: "/{{ $app.name }}"
          backend:
            serviceName: "{{ $serviceName }}-{{ $app.name | replace "_" "-" }}"
            servicePort: {{ $servicePort }}
        {{- end }}
        - path: /adminApp
          backend:
            serviceName: "{{ $serviceName }}-security"
            servicePort: {{ $adminPort }}
{{- end -}}
