{{ if .Values.systemDataCollector.enabled }}
{{- $systemDataCollectorName := "system-dc" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "control-hub.fullname" . }}-{{ $systemDataCollectorName }}"
  labels:
    app.kubernetes.io/name: {{ $systemDataCollectorName }}
    app.kubernetes.io/component: "datacollector"
    app.kubernetes.io/part-of: {{ include "control-hub.name" $ }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "control-hub.chart" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $systemDataCollectorName }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $systemDataCollectorName }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: datacollector
        image: "{{ .Values.systemDataCollector.image.repository }}:{{ .Values.systemDataCollector.image.tag }}"
        imagePullPolicy: {{ .Values.systemDataCollector.image.pullPolicy }}
        ports:
        - containerPort: 18630
        readinessProbe:
          httpGet:
            path: /public-rest/ping
            port: 18630
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
{{ toYaml .Values.systemDataCollector.resources | indent 12 }}
    {{- if .Values.systemDataCollector.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.systemDataCollector.nodeSelector | indent 8 }}
    {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "control-hub.fullname" . }}-{{ $systemDataCollectorName }}"
  labels:
    app.kubernetes.io/name: {{ $systemDataCollectorName }}
    app.kubernetes.io/component: "datacollector"
    app.kubernetes.io/part-of: {{ include "control-hub.name" $ }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "control-hub.chart" . }}
spec:
  ports:
  - name: http
    port: 18630
    targetPort: 18630
    protocol: TCP
  selector:
    app.kubernetes.io/name: {{ $systemDataCollectorName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- if .Values.istio.enabled }}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: "{{ include "control-hub.fullname" . }}-{{ $systemDataCollectorName }}"
  labels:
    app.kubernetes.io/name: {{ $systemDataCollectorName }}
    app.kubernetes.io/component: "datacollector"
    app.kubernetes.io/part-of: {{ include "control-hub.name" $ }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "control-hub.chart" . }}
spec:
  host: "{{ include "control-hub.fullname" . }}-{{ $systemDataCollectorName }}.{{ .Release.Namespace }}.svc.cluster.local"
  trafficPolicy:
    tls:
      {{- if eq .Values.istio.mTLS "DISABLE" }}
      mode: DISABLE
      {{ else }}
      mode: ISTIO_MUTUAL
      {{- end }}
---
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "{{ include "control-hub.fullname" . }}-{{ $systemDataCollectorName }}"
  labels:
    app.kubernetes.io/name: {{ $systemDataCollectorName }}
    app.kubernetes.io/component: "datacollector"
    app.kubernetes.io/part-of: {{ include "control-hub.name" $ }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "control-hub.chart" . }}
spec:
  targets:
  - name: "{{ include "control-hub.fullname" . }}-{{ $systemDataCollectorName }}"
  peers:
  - mtls:
      mode: {{ .Values.istio.mTLS }}
{{- end }}
{{- end }}
