{{- if .Values.istio.enabled }}
{{- $serviceName := include "control-hub.fullname" . -}}
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: {{ include "control-hub.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "control-hub.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "control-hub.chart" . }}
spec:
  targets:
  {{- range $app := .Values.apps }}
  - name: "{{ $serviceName }}-{{ $app.name | replace "_" "-" }}"
  {{- end }}
  peers:
  - mtls:
      mode: {{ .Values.istio.mTLS }}
---
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "{{ include "control-hub.fullname" . }}-db"
  labels:
    app.kubernetes.io/name: "{{ include "control-hub.name" . }}-db"
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "control-hub.chart" . }}
spec:
  targets:
  - name: "{{ include "control-hub.fullname" . }}-influxdb"
  - name: "{{ include "control-hub.fullname" . }}-mysql"
  peers:
  - mtls:
      mode: {{ .Values.istio.mTLS }}
{{- end }}
