---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "control-hub.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "control-hub.name" . }}
    helm.sh/chart: {{ include "control-hub.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{ if .Values.adminPassword -}}
  admin-password: {{ .Values.adminPassword | b64enc | quote }}
  {{ else -}}
  admin-password: {{ randAlphaNum 12 | b64enc | quote }}
  {{ end -}}
  {{ if .Values.schInfluxPassword -}}
  influxdb-password: {{ .Values.schInfluxPassword | b64enc | quote }}
  {{ else -}}
  influxdb-password: {{ randAlphaNum 12 | b64enc | quote }}
  {{ end -}}
  {{ if .Values.mailPassword -}}
  mail-password: {{ .Values.mailPassword | b64enc | quote }}
  {{- end -}}
